# docker-compose.yml
version: "3"
services:
  app:
    restart: on-failure
    build: .
    depends_on:
      - postgres
    environment:
      PGPDUSER: ottoUser
      PGPDPASSWORD: ottoPassword
      PGPDDATABASE: ottoDB
      PGPDHOST: postgres
      NODE_ENV: production
      ENCRYPT_PATH: otto_keys
      PORT: 3001
    ports:
      - "3001:3001"
    command: npm start
    volumes:
      - .:/app/
      - /app/node_modules

  postgres:
    image: postgres:11
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ottoUser
      POSTGRES_PASSWORD: ottoPassword
      POSTGRES_DB: ottoDB
      PGHOST: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d/setup.sql:/docker-entrypoint-initdb.d/setup.sql

volumes:
  pgdata: {}
